/**
 * The executor: how an under-specified action is read.
 *
 * A vague action is not undefined, it is *multi-defined*.  `R(a)` is the set of designs
 * the action plausibly denotes, generated by the fixed rule set the paper publishes:
 * what the executor must guess depends on which fields the agent wrote down, and the
 * action *type* selects how much of the design the completion rule invents.
 *
 * Ported from `run_action_construction_sim.py` (`resolver`, `_arms_for_focus`,
 * `_target_focus`).
 */
import { conditionOk, specFor, trueH } from './environment.js';
function sortedUnique(values) {
    return [...new Set(values.map((v) => Math.trunc(v)))].sort((a, b) => a - b);
}
/** The arms an executor runs when its attention is `focus`. */
function armsForFocus(env, focus, maxArms) {
    const th = trueH(env);
    const scores = [];
    for (let arm = 0; arm < env.m; arm++) {
        let score = 0;
        for (let h = 0; h < env.k; h++)
            if (th[h] === arm)
                score += focus[h];
        scores.push({ arm, score });
    }
    // stable: equal scores keep arm order, matching the Python sort
    scores.sort((a, b) => b.score - a.score || a.arm - b.arm);
    return sortedUnique(scores.slice(0, maxArms).map((s) => s.arm));
}
/** Attention induced by naming a target mechanism. */
function targetFocus(env, target, spec) {
    const uniform = 1 / env.k;
    const w = new Array(env.k).fill(0.2 / Math.max(1, env.k - 1));
    w[target] = 0.8;
    const sum = w.reduce((a, b) => a + b, 0);
    for (let i = 0; i < w.length; i++)
        w[i] /= sum;
    const sharp = 0.5 + 0.5 * spec.resolution_pressure;
    return w.map((x) => sharp * x + (1 - sharp) * uniform);
}
/** Plausible quantifications of an action: the reading set `R(a)`. */
export function readingSet(action, env) {
    const spec = specFor(action);
    const hasTarget = action.target !== null && action.target !== undefined;
    const hasArms = action.arms !== null && action.arms !== undefined;
    const hasN = action.n !== null && action.n !== undefined;
    // fully specified: one quantification, no guessing about the design
    if (hasArms && hasN) {
        return [{ arms: sortedUnique(action.arms), n: Math.trunc(action.n) }];
    }
    const nOptions = hasN
        ? [Math.trunc(action.n)]
        : [spec.n_default, spec.n_generous];
    let candidates;
    if (hasArms) {
        const arms = sortedUnique(action.arms);
        candidates = nOptions.map((n) => ({ arms, n }));
    }
    else if (hasTarget) {
        const arms = armsForFocus(env, targetFocus(env, action.target, spec), spec.max_arms_default);
        candidates = nOptions.map((n) => ({ arms, n }));
    }
    else {
        // no intent written down: the executor must infer the intent itself, and which arm
        // family it picks is exactly what the agent failed to say
        const generic = [0];
        const broad = [0, 1];
        const scan = [0, 1, 2, 3];
        candidates = [
            { arms: generic, n: spec.n_default },
            { arms: broad, n: spec.n_default },
            { arms: scan, n: spec.n_default },
            { arms: generic, n: Math.min(spec.n_generous, 4) },
        ];
    }
    const seen = new Set();
    const out = [];
    for (const candidate of candidates) {
        const key = `${candidate.arms.join(',')}|${candidate.n}`;
        if (seen.has(key))
            continue;
        if (!conditionOk(env, candidate.arms))
            continue;
        seen.add(key);
        out.push(candidate);
    }
    return out.length > 0 ? out : [{ arms: [0], n: 2 }];
}
/** `1 - 1/|R(a)|`: the share of the design the executor had to invent. */
export function guessRate(quantifications) {
    if (quantifications.length === 0)
        return 1;
    return 1 - 1 / quantifications.length;
}
//# sourceMappingURL=executor.js.map