/**
 * The executor: how an under-specified action is read.
 *
 * A vague action is not undefined, it is *multi-defined*.  `R(a)` is the set of designs
 * the action plausibly denotes, generated by the fixed rule set the paper publishes:
 * what the executor must guess depends on which fields the agent wrote down, and the
 * action *type* selects how much of the design the completion rule invents.
 *
 * Ported from `run_action_construction_sim.py` (`resolver`, `_arms_for_focus`,
 * `_target_focus`).
 */
import type { Design, Env, Quantification } from './types.js';
/** Plausible quantifications of an action: the reading set `R(a)`. */
export declare function readingSet(action: Design, env: Env): Quantification[];
/** `1 - 1/|R(a)|`: the share of the design the executor had to invent. */
export declare function guessRate(quantifications: readonly Quantification[]): number;
//# sourceMappingURL=executor.d.ts.map